// JS usa padrão decimal americano, dividindo casas decimais com "."
//Exemplo: 1.90

//quando usar palavras especiais tipo "var" chame em letra minuscula

//JS é uma linguagem de match case (se ta com letra maiuscula na hora da atribuição, tem que estar na hora de chamar a var)

// "var" é igual a "let"
// apesar de dar para construir uma variavel usando direto o nome dela 
//exemplo: Trabalho= analista de sistemas
//A forma mais correta é usando :
//var trabalho = analista de sistemas;
//ou
//let trabalho = analista de sistemas;
//nunca (sem var ou let)
//trabalho = analista de sistemas;
//constantes são escritas em letras maiusculas
//exemplo:PI
// \n significa new line (nova linha)
// o \n é um caracter especial que não aparece no console. Para ele aparecer:
// boa como gambiarra uma bara a mais (igual ao $ a mais no automation anywhere, para o caracter nao ser lido como especial)
// t da um tab

//"E" = && para operações logicas - & para operaçoes binarias resultado 0 e 1)
//ou = || (pipe)operações logicas - & para operaçoes binarias resultado 0 e 1)
//ou exclusivo para operações binárias = ^
// ou exclusivo para operações lógicas !=
//ou exclusivo para operações lógicas !== (extritamente diferente)
// Not (negação) ! -> exemplo console.log(!true);