// JS usa padrão decimal americano, dividindo casas decimais com "."
//Exemplo: 1.90

//quando usar palavras especiais tipo "var" chame em letra minuscula

//JS é uma linguagem de match case (se ta com letra maiuscula na hora da atribuição, tem que estar na hora de chamar a var)

// "var" é igual a "let"
// apesar de dar para construir uma variavel usando direto o nome dela 
//exemplo: Trabalho= analista de sistemas
//A forma mais correta é usando :
//var trabalho = analista de sistemas;
//ou
//let trabalho = analista de sistemas;
//nunca (sem var ou let)
//trabalho = analista de sistemas;
//constantes são escritas em letras maiusculas
//exemplo:PI

