// JS usa padrão decimal americano, dividindo casas decimais com "."
//Exemplo: 1.90

//quando usar palavras especiais tipo "var" chame em letra minuscula

//JS é uma linguagem de match case (se ta com letra maiuscula na hora da atribuição, tem que estar na hora de chamar a var)

// "var" é igual a "let"
// apesar de dar para construir uma variavel usando direto o nome dela 
//exemplo: Trabalho= analista de sistemas
//A forma mais correta é usando :
//var trabalho = analista de sistemas;
//ou
//let trabalho = analista de sistemas;
//nunca (sem var ou let)
//trabalho = analista de sistemas;
//constantes são escritas em letras maiusculas
//exemplo:PI
// \n significa new line (nova linha)
// o \n é um caracter especial que não aparece no console. Para ele aparecer:
// boa como gambiarra uma bara a mais (igual ao $ a mais no automation anywhere, para o caracter nao ser lido como especial)
// t da um tab

//"E" = && para operações logicas - & para operaçoes binarias resultado 0 e 1)
//ou = || (pipe)operações logicas - & para operaçoes binarias resultado 0 e 1)
//ou exclusivo para operações binárias = ^
// ou exclusivo para operações lógicas !=
//ou exclusivo para operações lógicas !== (extritamente diferente)
// Not (negação) ! -> exemplo console.log(!true);

// obs: se quero imprimir numa string " (aspas duplas) escrevo a string com aspas simples '
// caso queira o contrário: se quero imprimir numa string ' (aspas simples) escrevo a string com aspas duplas "
// o barra \ também auxilia tirando o caracter especial da sua função especial;

// da para escrever a expressão console.log('vamos comprar a TV de 50"',trabalho1 && trabalho2) separando por vigulas
// a virgula também concatena  e adiciona espaço;
// outra opção é o +
//a++
//a--
// negaçao devalores que não sao tipicamente true or false
// shif alt F formatar código


// if não se coloca ; senao o if age em cima do ; seguinte e nao do bloco a seguir
// if, while, for ->>> retorna valores verdadeiros (ou falsos)
//switch retorna outros valores que não são nem verdadeiro e nem falso.
//No if e else você consegue definir um intervalo, já no switch não, tem que se o "case" exato

// Duplicar um código : seleciona o trecho e digita :ALT + SHIFT + (setinha pra baixo)
// o break ele termina o laço for.
// o continue não sai do laço, ele vai para a proxima repetição

//Return: quando o codigo chega na palavra return, ele sai do metodo e não executa nada que venha depois

//Para comparar 3 valores ou mais em uma função (funções so utilizam dois valores por vez) é só repetir a função

// Você pode colocar função dentro de uma variavel em JavaScript (nem toda linguagem apresenta isso)

//function anonima = função sem nome 
// uma função sem nome/ anonima pode ser armazenada numa variavel
//a função anonima só pode ser criada (sem gerar erro), sendo atribuida por uma variavel
//outra opção é variavel receber funcao como valor atribuido
